### ISSUE TITLE
Does code meet majority of requirements ? 

### ISSUE THREAD

**Issue by rezabashiri** [AccentDesign/modular_dotnet_boilerplate#1]
This is the first publishing of modular Dotnet boilerplate and it aims to give the ability of following DDD in monolith clean application.

Before further investigation, we are at a good point to look over the repo and extract potential required changes

**Comment by craigvincent** [comment]
@rezabashiri could you open a PR from `initial` instead of the issue ticket, it'll enable us to reference code a little easier please :)
